### ISSUE TITLE
support extension methods for submit/fetch

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#184]
We don't support extension methods in submit/fetch but there are some exercises like (strain) that are meant with that in mind. Also, I think we should teach people that "monkey patch" is not an evil thing.

Probably should contemplate this after #129 .

I'm thinking we could have a pragma like: <exercism: #ExerciseNameTest> and then we could ensure that methods tagged with this were written out (the issue is that extensions can only live at the package level and not the sub-package/tag level). A bit frustrating as the tags otherwise give a great end-user experience to keep all of the exercises neatly together.

I think the trade-off that a few extension methods sitting in the top level 'Exercism' and the requirment to use the above pragma should be ok?

**Comment by macta** [comment]
If we use Pragmas - there is Pragma allNamed: aSymbol in: aClass (can't see it for package, but I guess you can loop over classes in a package and then find them that way)

**Comment by bencoman** [comment]
I'm mulling over whether that might end up building a false habit/impression unsuited for normal Pharo.
The other idea floating through my head is to make each exercise a full package.
To distinguish exercises from our Exercism infrastructure, top-level packages would be...
- Exercise-HelloWorld
- Exercise-SpaceAge
- Exercise-TwoFer

PRO
- extensions work without any semantic changes to Pharo
- better code organisation of exercises on github rather than all lumped under on package "Exercism"
   https://github.com/exercism/pharo-smalltalk/tree/master/dev/src/Exercism

CON
- bulks out top-level package list

**Comment by macta** [comment]
It's a tough one ...

I'm not sure if its really a pro about the code organisation from a github pov (I don't think it makes any difference either way - to it, they are just files, and code review etc works fine).

As another con - with a top level package its super easy to delete all the exercises and WIP exercies as you just do a single top level delete.

I think we could easily explain a pragma in the relevant exercises - so I'm not sure it has to set any sort of precedent - and I don't think there will be many exercises where it actually gets used (maybe just 2).

But yeah - I'm torn too - its a shame the tags are modelled so badly in Pharo.

**Comment by bencoman** [comment]
So we bit the bullet and #302 is converting exercises to full packages.
Working with the **Die** exercise test case, I've implemented uploading of extensions. See PR above.
Here is a copy of the solution as viewed from my Exercism web interface... [Ben'sUploadedDieSolutionFromWebView.txt](https://github.com/exercism/pharo-smalltalk/files/3170136/Ben.sUploadedDieSolutionFromWebView.txt)
