### ISSUE TITLE
Use Error rather than Exception

### ISSUE THREAD

**Issue by bencoman** [exercism/pharo-smalltalk#300]
Use of **Exception** is too broad and should instead at least be **Error** rather than **Exception**, 
since `self halt` is an exception the debugger is prevented from opening at the correct location.
```
test15_RollsCannotScoreNegativePoints 
    self
		should: [ result := bowlingCalculator scoreRolling: -1 after: #() ]
		raise: Exception
```
https://github.com/exercism/pharo-smalltalk/blob/bcc3c4a929dc103069ca8b61cf8f15cf4c3eface/dev/src/Exercism/BowlingTest.class.st#L228 

Even better would be to demonstrate using custom errors (will submit an example soon), since MessageNotUnderstood errors are masked and the debugger opens in the wrong place and the exception is not available for inspection making it doubly hard to determine what went wrong.

**Comment by macta** [comment]
Ben - good spot, I mean to generate Error (not Exception, I got it backwards).

The idea was that it wouldn't preclude people from using something like DomainError, or creating their own custom exception. However, so far none of the exercises have actually specified a specific Exception (and thus caused users to create their own) - so its we should have a specific one, or nominate one of the exercises to specify one (Bowling might be a good example, but there is a lot going on there, so maybe one of the earlier ones).

If we do override, to something specific, we really ought to sort out the generator - regeneration stories otherwise regenerting will blast over that override. For now, I've been creating a #generator method, that returns a collection of overrides (its not used yet - but the idea was we might be able to use something like this to customize the code when we regenerate it vs using defaults.

**Comment by macta** [comment]
I've realised my confusion is that because in Java its the other way around - I wonder why we consider an Error less severe than an Exception?

**Comment by bencoman** [comment]
Smalltalk hierarchy is Object > Exception > Error
I'm not familiar with Java but the diagram here shows they are
siblings rather than opposite.
http://www.javawithus.com/tutorial/exception-hierarchy

(https://www.cs.cmu.edu/~pattis/15-1XX/15-200/lectures/exceptions/index.html)
says...
"The class Error and its subclasses indicate something wrong with Java
itself. It is recommended that programs not throw, or attempt to
catch, these errors, but instead let Java itself throw and terminate
any program throwing them. Thus, we have and will continue to focus on
the class Exception and the subclasses its hierarchy."

So one difference is Java "Errors" are expected to be unrecoverable
and terminate the program,
but the Smalltalk executable (the VM) never terminates.
Smalltalk "Errors" are always handled, even it only caught by the code
that invokes the debugger.

By comparative positions in the inheritance hierarchy, Smalltalk
"Exception" seems more equivalent to Java "Throwable".
I've no clue what the Smalltalk equivalent where Java distinguishes
between checked and unchecked Exceptions.
