### ISSUE TITLE
Resisitor ColorDuo  (GRVariableAssignedLiteralRule) 

### ISSUE THREAD

**Issue by RoelofWobben** [exercism/pharo-smalltalk#343]
I have this in my class  : 

Object subclass: #ResistorColorDuo
	instanceVariableNames: 'colourCodes'
	classVariableNames: ''
	package: 'Exercise@ResistorColorDuo'

and this as method : 

colourCodes
	^ colourCodes
		ifNil:
			[ colourCodes := #('black' 'brown' 'red' 'orange' 'yellow' 'green' 'blue' 'violet' 'grey' 'white') ]

but critiz do not like it.

**Comment by macta** [comment]
can you pop the screen shot like with others, it makes it more obvious what you are getting at.

**Comment by RoelofWobben** [comment]
of course 

![afbeelding](https://user-images.githubusercontent.com/47429430/57720140-8c681180-7681-11e9-832c-0835c6f2dd28.png)

**Comment by bencoman** [comment]
@roelofWobben, Those screen shots help a lot.  thx.  For next similar issues, could you also copy the advice text to the issue.  A lot of these critics are new to me.  I think what this one is saying is that if this is the only method setting that variable to a literal, you would be just as good with...
```
colourCodes
    ^ #('black 'brown' .... etc)
```

**Comment by bencoman** [comment]
Would that fit your code?  (sorry for the split post - comment editing is not working from this machine for some reason)

btw, Remember these are just suggestions. Not all rules are correct for all situations and can't take into account future plans for the design to evolve.  Consider they are there to give you additional insight rather than being absolute, and sometimes pick up unintended cases for which end-user feedback is valuable to tune them.

**Comment by macta** [comment]
The suggestion is actually correct - you don't need the variable (or need to lazy init it)

**Comment by RoelofWobben** [comment]
oke, I learned from one of you two to use lazy inits but I will change the code

**Comment by RoelofWobben** [comment]
this one is solved this way and deleted it from the instance variables

**Comment by bencoman** [comment]
On Wed, 15 May 2019 at 13:01, RoelofWobben <notifications@github.com> wrote:

> oke, I learned from one of you two to use lazy inits but I will change the
> code
>
Lazy inits if often a good way to go, but like everything its not an
absolute rule.
Its more useful in TDD since in the debugger you are looking at an object
that ran #initialize a some time ago.

cheers -ben

**Comment by macta** [comment]
To add further - this is a static array of strings that isn’t very big - so prime candidate for just a method returning the array (which is very efficient).

Lazy inky was encouraged on Planet as it was a  Dictionary of key/pairs . Not huge, but a more complicated beast - edging you over to a lazy init.

That’s the lesson (and a good mentor note to pop somewhere). Ben would you agree?

**Comment by bencoman** [comment]
Agreed. Since #asDictionary is sent to the literal array of pairs, its a
different case.
Without lazy initialization a new Dictionary would be created every time,
which in general is pointless, and in some situations could be a bad idea.
By mentor note, do you mean note-to-selves, or note-to-students.  Perhaps
the place to mention it is where lazy initialization is first described.

**Comment by macta** [comment]
By mentor note I was thinking of the notes we put in the reference implementation comment that would form a basis for feedback (and in this case could be a nice critic rule in the planet example).

But - the exercise hint could point to an article on the difference as we’ve described?

It’s how to build up practical material?
