### ISSUE TITLE
Recruiting additional maintainers for Pharo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/pharo-smalltalk#402]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by samWson** [comment]
@kytrinyx I first proposed this language track sometime ago and have been a maintainer since. Due to Pharo's unique image based programming environment a lot of custom code has been built to make it work with Exercism. I had the help of some people who have managed to build something amazing in a very short time. However this track has stagnated as none of the existing maintainers have had the time available to continue development.

I can see on the Pharo discord that people are still using the Pharo language track, though I don't have accurate numbers. So I am still interested in maintaining what we have. Without the help of others I am having to learn a lot of the existing code from scratch in order to improve things, so it is slow going.

Regarding Exercism v3 I'm not sure if it is a goal for this track as I don't know what is required or how much work is needed to make it happen.

**Comment by iHiD** [comment]
> Regarding Exercism v3 I'm not sure if it is a goal for this track as I don't know what is required or how much work is needed to make it happen.

@samWson - just to answer the question of what's required. Two things:
- A test runner
- 20 new Concept Exercises written

The [v3 repo](https://github.com/exercism/v3) has lots of docs, and if you'd like more info, maybe you want to arrange a time to chat to @ErikSchierboom on Slack?

Thanks for all your work so far 💙

**Comment by samWson** [comment]
@iHiD where can I find the Slack?

**Comment by iHiD** [comment]
It's at exercism-team.slack.com :)

If you don't have an invite, email me at jeremy@exercism.io
Signing up to be a mentor through the website also automatically sends you an invite.

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
