### ISSUE TITLE
Roadmap - Where are we? Where do we want to go?

### ISSUE THREAD

**Issue by samWson** [exercism/pharo-smalltalk#403]
Hi @macta and @bencoman.

I've been wanting to get back to this repository and get it out of its somewhat stalled state. 

From what I can see we have a working solution here. People can do exercises and get feedback. We have some issues that need to be fixed to make long term maintenance viable.

From what I can see issue #370 and pull request #372 are the major outstanding items that need to be done.

@macta when we met in London you suggested something along the lines of having two repositories. One that contains only the code developed in image and the other containing all the artifacts needed for the exercism website. A build process produces the latter from the first. This is an idea I like and want to get done.

If the two of you could tell me what you think needs to be done to move things forward that would be great.

I realize no one has really had the time to dedicate to this repository. I have no problem with that. I want to get things moving myself, I just need to know what needs doing and if either of you want to have any input in the process. If all else fails then I want to at least leave this repository in a state where someone else can pick up maintenance from where we left off.

**Comment by bencoman** [comment]
Thanks for the bump Sam.  I've let this slide too long.   My discretionary time has been taken up with  helping Richard Eng out with his programming competition.  That finishes up in a couple of weeks.  So that will free me up a bit to complete those two PRs.

**Comment by samWson** [comment]
Thanks @bencoman. I'll watch out for your work.

**Comment by RoelofWobben** [comment]
News on this matter ?   I find it very pity that this seems to be "dead".  Is there maybe a way  this could be a active one again and maybe work on exercism v3.

**Comment by samWson** [comment]
Hi @RoelofWobben. I've been reluctant to make changes without the help of the other maintainers. Most of the code has been written by them and they understand it far better than I do. For whatever reason they are just not able to help so I haven't been maintaining the repo either.

At this point I'm assuming I'll get no help from the others. If I want development to continue I will have to pick up where they left off myself and learn along the way. 

First I want to address some of the simpler open issues. Doing some of those might give me an idea of where future development will be difficult.

Next I want to lower the barrier for new contributors to help maintain the repo. I know from my own experience that just getting a development environment set up has a lot of manual steps. That's plenty of things that can go wrong and deter new contributors. Anything that can make the process take fewer steps is an improvement.

Related to the above I also want to make the repository less complex. It is currently composed of the image development source code and the exercism-pharo website source code. One of the manual steps we have to take is to generate the website code from the image code. An idea that was suggested is to have two repositories: one containing all the development source code for the image and the other containing all the generated code for the website. The latter of the two is automatically generated by the first. This would go a long way to simplifying development.

The last point is to consider Exercism v3. I haven't given it much attention so I don't know what it means for the Pharo Smalltalk language track. It will likely require a lot of work so I want to make sure development is sustainable before I make any moves toward v3.

**Comment by RoelofWobben** [comment]
Thanks for the clarifiation

**Comment by macta** [comment]
Hi guys -good to hear you are interested in keeping the ideas alive. Unfortunately lockdown hasn’t given me more time to help  (the opposite actually, particularly with home schooling on the table too).

Sam’s comment on the barrier to contribution Is a good one. We proved all this can work, but building up a portfolio of complete exercises was tough because the steps to do it (generating them to re-include them for the exercism site) are not what people expect, and so it made things quite hard.

In retrospect Sam initially had the right idea that the exercises should be in a separate repo from the dev environment, but I would suggest doing it differently from how we/he originally imagined.

I would figure out how to automate the generation steps on a successful Travis build (it maybe a GitHub action now?), and I would automatically push the generated Tonel to the official Exercism site that backs the Pharo track. This way it looks like any other language, to exercism. The trick is how to do an inter/repo push? My devops foo on this is a bit basic but I’m pretty sure it can be done. 

I think this would simplify things a lot - from a dev perspective, you take our current repo (which you move out of official exercism), you get your example running and tests passing, you create a PR, and when merged it then gets pushed over to the exercism site which makes it available.

Hope this helps.

Tim
