### ISSUE TITLE
Create Pharo todo url

### ISSUE THREAD

**Issue by macta** [exercism/pharo-smalltalk#45]
The current readme.md refers to  http://exercism.io/languages/pharo/todo Which resolves to generic exercism help and not Pharo specific help.

Can we tag  issues as being suitable for this url?

**Comment by macta** [comment]
@samWson this would be a good one to look at if you have limited time - maybe we can get rid of our other repo as well?

**Comment by samWson** [comment]
@macta I'll get started on this. Might need a bit of time to familiarize myself with the workings of Exercism.

**Comment by macta** [comment]
I notice that csharp has a good discussion on ordering of exercise (potential todo’s)

https://github.com/exercism/csharp/issues/611

**Comment by samWson** [comment]
I just merged #90 to remove the link from the README since it seems redundant. If we want an exercise todo list, the easiest think might be a TODO.md document in the `/doc` directory. There are a lot of exercises in the [problem specifications repo](). To save us typing them all out we could add to the list of exercises we intend to do in the near future, unless there is some handy way of generating a list of them all.

**Comment by samWson** [comment]
I'll close this for now since it has been dormant for a long time and is a low priority at the moment. We can always revisit this later.
