### ISSUE TITLE
Error downloading "grains" on exercism v3

### ISSUE THREAD

**Issue by moniquelive** [exercism/pharo-smalltalk#499]
Using Pharo 9:

- right click on the Browser -> Exercism -> Fetch new exercise
- typed "grains"

![image](https://user-images.githubusercontent.com/70070/132735064-8c2d096d-b279-493c-b67e-fff01c98cf00.png)

**Comment by RoelofWobben** [comment]
yep, we are investigating this problem

**Comment by Bajger** [comment]
The root cause of this problem is in obtaining empty stub file from Exercism server:
As you can see, dev environment tries to get void resource through HTTP client, it returns nil object, since stub file is empty:
![obrazek](https://user-images.githubusercontent.com/45875448/132804266-b377f6bf-bef5-4e7e-99cc-f6025cb6147c.png)
This is not because of non-existent file (as claimed in screenshot), but because file is empty: 
![obrazek](https://user-images.githubusercontent.com/45875448/132804130-37e05603-012a-48fe-8503-92a8143e6c8c.png)

**Comment by gypsydave5** [comment]
@moniquelive - the fix has been merged and so (should be) live. Give it all a go again with a fresh image?

**Comment by RoelofWobben** [comment]
or use these upgrade instructions : https://github.com/exercism/pharo-smalltalk/blob/main/docs/UPGRADE.md

**Comment by moniquelive** [comment]
Amazing! Thank you very much you guys! All good it seems 👌
